apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/mertcakmak2/Kubernetes-SpringBoot.git
    targetRevision: HEAD
    path: dev
  destination:
    server: a101df0ffc3c24ee4a9943faf908cff3-1017186682.us-west-2.elb.amazonaws.com
    namespace: app
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true