apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-lneu
  namespace: argo-cd
spec:
  destination:
    name: ''
    namespace: app
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests
    repoURL:  https://github.com/luisfneu/spring-boot-app-demo.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true