apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout-bluegreen
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-bluegreen-active
            port:
              number: 80